category
AlenaVyrodova/bookStore pull request #10
Opened 2023-12-14 10:10 UTC by AlenaVyrodova

2023-12-14 12:07 UTC, Sanderfuck requested changes

2023-12-14 12:07 UTC, Sanderfuck commented on src/main/java/com/example/bookstore/controller/CategoryController.java
> +
```suggestion

```

2023-12-14 12:07 UTC, Sanderfuck commented on src/main/java/com/example/bookstore/dto/book/CreateBookRequestDto.java
> +     BigDecimal price,
Poor validation

2023-12-14 12:07 UTC, Sanderfuck commented on src/main/java/com/example/bookstore/dto/category/CreateCategoryRequestDto.java
> +        String description) {
What about valid description?

2023-12-14 12:07 UTC, Sanderfuck commented on src/main/java/com/example/bookstore/model/Book.java
> +
```suggestion

```

2023-12-14 12:07 UTC, Sanderfuck commented on src/main/java/com/example/bookstore/service/CategoryService.java
> +
```suggestion

```

2023-12-14 12:07 UTC, Sanderfuck commented on src/main/java/com/example/bookstore/service/imp/CategoryServiceImpl.java
> +
```suggestion

```

2023-12-14 12:07 UTC, Sanderfuck commented on src/main/java/com/example/bookstore/service/imp/CategoryServiceImpl.java
> +
```suggestion

```

2023-12-14 12:07 UTC, Sanderfuck commented on src/main/java/com/example/bookstore/service/imp/CategoryServiceImpl.java
> +
```suggestion

```

2023-12-14 12:07 UTC, Sanderfuck commented on src/main/java/com/example/bookstore/service/imp/CategoryServiceImpl.java
> +
```suggestion

```

2023-12-15 09:26 UTC, Rommelua approved these changes

2023-12-27 08:24 UTC, merged